### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by irinatu** [Weeks-UNC/Superfold#7]
Do you consider to adapt the program to python3?

**Comment by Psirving** [comment]
Hello again! A python3 version is being developed. If you used `git clone` to install Superfold, you can switch to python3 by typing `git checkout python3` from the Superfold directory. It has not been tested in any way yet, so you might encounter errors.

**Comment by irinatu** [comment]
Hello, unfortunately it is not enough. When I jus run Superfold for python3 version I obtained:
Superfold.py Sim.map                           
/home/irina/bin/Superfold/Superfold.py:83: DeprecationWarning: 'U' mode is deprecated
  for line in open(fIN, "rU").readlines():
Traceback (most recent call last):
  File "/home/irina/bin/Superfold/Superfold.py", line 1421, in <module>
    main()
  File "/home/irina/bin/Superfold/Superfold.py", line 113, in main
    args = parseArgs()
  File "/home/irina/bin/Superfold/Superfold.py", line 740, in parseArgs
    m.update(str(o.mapFile))
TypeError: Strings must be encoded before hashing

After changing "rU" to newline=None or  newline='':
Superfold.py Sim.map
Traceback (most recent call last):
  File "/home/irina/bin/Superfold/Superfold.py", line 1421, in <module>
    main()
  File "/home/irina/bin/Superfold/Superfold.py", line 113, in main
    args = parseArgs()
  File "/home/irina/bin/Superfold/Superfold.py", line 740, in parseArgs
    m.update(str(o.mapFile))
TypeError: Strings must be encoded before hashing:

**Comment by Psirving** [comment]
This has something to do with how strings are encoded in python2 vs python3. Lines 740-747 should be something like `m.update(o.variableName.encode('utf-8'))` instead of `m.update(str(o.variableName))`. I can't guarantee that will work or that you won't encounter more errors.

'U' mode was not causing the error, only a warning. Since 'U' mode is the new default, python is telling you that it is not necessary.
